idf_component_register(
    SRCS
        "display.cpp"
        "ble_bridge.cpp"
        "main.cpp"
        "voice_module.cpp"
    INCLUDE_DIRS
        "."
    REQUIRES
        driver
        esp_http_server
        esp_lcd
        esp_timer
        esp_wifi
        bt
        mdns
        nvs_flash
)
